# Dependencies
markdown: kramdown
kramdown:
  extensions: ["tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            Transit Passenger Survey 
tagline:          'Metropolitan Transportation Commission'
url:              http://bayareametro.github.io/transit-passenger-surveys/
baseurl:          /transit-passenger-surveys
shorturl:         bayareametro.github.io/transit-passenger-surveys/

author:
  name:           'Shimon Israel'
  url:            https://github.com/shimonisrael

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/BayAreaMetro/transit-passenger-surveys/tree/gh-pages

# This is the list of pages to include in the header of the website.
pages_list:
  # Steering: '/steering/'
  Schedule: '/schedule/'  
  Standard Operating Procedures: '/SOP/'
  Data/Reports: '/data/'
  Policy/Papers: '/papers/'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
plugins:
  - jekyll-redirect-from
