---
title: "Route Level Analysis"
output:
  html_document:
    theme: cosmo
    toc: yes
editor_options: 
  chunk_output_type: console
---

## Administration

#### Purpose
Decomposition at the route level. TODO: add more
Current thinking: build CSV database, read and analyze in Tableau

#### Issues
Everything, early days

## Overhead

#### Libraries
```{r overhead}
list_of_packages <- c(
  "tidyverse",
  "knitr"
  )

new_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,"Package"])]

if(length(new_packages)) install.packages(new_packages)

for (p in list_of_packages){
  library(p, character.only = TRUE)
}
```

#### Knitr and global config
```{r config, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, error = TRUE)

options(stringsAsFactors = FALSE)
```

#### Remote IO
```{r user_lookup, echo = FALSE}
user_list <- data.frame(user = c("helseljw", "USDO225024"), 
  path = c("../../Data and Reports/", 
           "~/GitHub/onboard-surveys/Data and Reports/"))

dir_path <- user_list %>%
  filter(user == Sys.getenv("USERNAME")) %>%
  .$path

f_decomposition_file_name <- paste0(
  dir_path, "_data Standardized/decomposition/survey_decomposition.RDS")

f_canonical_route_names_file_name <- paste0("temp_canonical_route_names.csv")

f_standard_crosswalk_file_name <- paste0("temp_standard_route_crosswalk.csv")

f_output_file_name <- paste0("route_level_analysis.csv")

remove(user_list)

```

#### Data Reads
```{r data-reads}
input_df <- readRDS(f_decomposition_file_name)

# TODO fix muni hacks
crosswalk_df <- read.csv(f_standard_crosswalk_file_name, header = TRUE, colClasses = c("NULL", rep("character", 5))) %>%
  mutate(survey = ifelse(survey == "SFMTA", "SF Muni", survey)) %>%
  mutate(year = ifelse(survey == "SF Muni", "2017", year))

# TODO: add legacy surveys when we get there


```

#### Analysis
```{r analysis}
get_sequence <- function(data_df, operator_string, route_string, label_string) {
  
  # data_df <- working_df 
  # operator_string <- "intercept_operator"
  # route_string <- "intercept_route"
  # label_string <- "intercept"
  
  vars <- c(operator = operator_string, route = route_string)
  
  if (operator_string == "intercept_operator") {
    
    return_df <- working_df %>%
      select(vars, survey_year, weekpart, weight, trip_weight) %>%
      group_by(survey_year, weekpart, operator, route) %>%
      summarise(boardings = sum(weight), trips = sum(trip_weight)) %>%
      ungroup() %>%
      mutate(label = label_string,
             intercept_operator = operator) 
    
    
  } else {
    
    return_df <- working_df %>%
      select(vars, intercept_operator, survey_year, weekpart, weight, trip_weight) %>%
      group_by(intercept_operator, survey_year, weekpart, operator, route) %>%
      summarise(boardings = sum(weight), trips = sum(trip_weight)) %>%
      ungroup() %>%
      mutate(label = label_string)
    
  }
  
  return(return_df)
  
}


working_df <- input_df %>%
  rename(intercept_operator = operator, intercept_route = route)

running_df <- get_sequence(working_df, 
                           "intercept_operator",
                           "intercept_route",
                           "intercept")

running_df <- bind_rows(running_df,
                        get_sequence(working_df,
                                     "first_before_operator",
                                     "first_route_before_survey_board",
                                     "first_before"))

running_df <- bind_rows(running_df,
                        get_sequence(working_df,
                                     "second_before_operator",
                                     "second_route_before_survey_board",
                                     "second_before"))

running_df <- bind_rows(running_df,
                        get_sequence(working_df,
                                     "third_before_operator",
                                     "third_route_before_survey_board",
                                     "third_before"))
running_df <- bind_rows(running_df,
                        get_sequence(working_df,
                                     "first_after_operator",
                                     "first_route_after_survey_alight",
                                     "first_after"))

running_df <- bind_rows(running_df,
                        get_sequence(working_df,
                                     "second_after_operator",
                                     "second_route_after_survey_alight",
                                     "second_after"))

running_df <- bind_rows(running_df,
                        get_sequence(working_df,
                                     "third_after_operator",
                                     "third_route_after_survey_alight",
                                     "third_after"))

running_df <- running_df %>%
  mutate(tofrom_label = label) %>%
  mutate(tofrom_label = ifelse(str_detect(label, "before"), "from", tofrom_label)) %>%
  mutate(tofrom_label = ifelse(str_detect(label, "after"), "to", tofrom_label)) %>%
  select(survey_operator = operator,
         survey_route = route,
         survey_name = intercept_operator,
         survey_year,
         weekpart,
         survey_boardings = boardings,
         survey_trips = trips,
         survey_label = tofrom_label,
         survey_detail_label = label)


join_df <- crosswalk_df %>%
  rename(survey_name = survey, survey_year = year, survey_route = survey_name) %>%
  mutate(survey_year = as.integer(survey_year))

# TODO remove BART hack when crosswalk fixed
working_df <- left_join(running_df, join_df, by = c("survey_name", "survey_year", "survey_route")) %>%
  mutate(canonical_operator = ifelse(is.na(canonical_operator) & survey_operator == "BART", "BART", canonical_operator)) %>%
  mutate(canonical_name = ifelse(is.na(canonical_name) & survey_operator == "BART", survey_route, canonical_name)) %>%
  filter(!is.na(canonical_operator)) %>%
  select(-survey_route, -survey_operator) %>%
  rename(route = canonical_name, operator = canonical_operator) %>%
  group_by(operator, route, survey_name, survey_year, weekpart, survey_label, survey_detail_label) %>%
  summarise(survey_boardings = sum(survey_boardings), survey_trips = sum(survey_trips)) %>%
  ungroup() %>%
  filter(survey_boardings > 0 & survey_trips > 0)

trips_df <- working_df %>%
  select(-survey_boardings, -survey_label) %>%
  spread(key = survey_detail_label, value = survey_trips, fill = 0.0)

boardings_df <- working_df %>%
  filter(survey_label == "intercept") %>%
  select(operator, route, weekpart, survey_name, survey_year, survey_boardings)

output_df <- left_join(trips_df, 
                       boardings_df, 
                       by = c("operator", 
                              "route", 
                              "weekpart", 
                              "survey_name", "survey_year")) %>%
  mutate(survey_boardings = ifelse(is.na(survey_boardings), 0.0, survey_boardings))
  
# remove(working_df, boardings_df, trips_df, running_df)
```

#### Write to Disk
```{r write}
write.csv(output_df, file = f_output_file_name, row.names = FALSE, quote = TRUE)
```

