---
title: "Secondary Expansion"
output: html_notebook
---

# R Overhead
```{r overhead, include = FALSE}
packages_vector <- c("tidyverse",
                     "reticulate",
                     "reshape",
                     "reshape2",
                     "ggplot2",
                     "scales",
                     "plotly",
                     "htmlwidgets")

need_to_install <- packages_vector[!(packages_vector %in% installed.packages()[,"Package"])]

if (length(need_to_install)) install.packages(need_to_install)

for (package in packages_vector){
  library(package, character.only = TRUE)
}

```

# Python Overhead - Conda config (only need to run once)
```{bash}
conda create -n mtc_tps python=3.8
conda activate mtc_tps 
pip install populationsim
```

# Python Overhead - Conda activation Config
```{r python-config}
use_condaenv("mtc_tps")
```

# Clear cached files and execute procedures
```{r pre-game}

if (file.exists("./data/geogXWalk.csv")) {file.remove("./data/geogXWalk.csv")}
if (file.exists("./data/seed_controls.csv")) {file.remove("./data/seed_controls.csv")}
if (file.exists("./data/seed_households.csv")) {file.remove("./data/seed_households.csv")}
if (file.exists("./data/seed_persons.csv")) {file.remove("./data/seed_persons.csv")}
if (file.exists("./data/TPS_processed.csv")) {file.remove("./data/TPS_processed.csv")}

if (file.exists("./output/activitysim.log")) {file.remove("./output/activitysim.log")}
if (file.exists("./output/final_expanded_household_ids.csv")) {file.remove("./output/final_expanded_household_ids.csv")}
if (file.exists("./output/final_GEOID_weights.csv")) {file.remove("./output/final_GEOID_weights.csv")}
if (file.exists("./output/final_incidence_table.csv")) {file.remove("./output/final_incidence_table.csv")}
if (file.exists("./output/final_summary_hh_weights.csv")) {file.remove("./output/final_summary_hh_weights.csv")}
if (file.exists("./output/mem.csv")) {file.remove("./output/mem.csv")}
if (file.exists("./output/pipeline.h5")) {file.remove("./output/pipeline.h5")}
if (file.exists("./output/timing_log.csv")) {file.remove("./output/timing_log.csv")}

source("preprocess.R")

py_run_file("run_populationsim.py", local = FALSE, convert = TRUE)

source("postprocess.R")
```

