---
title: "Build Legacy Database"
author: "David Ory"
output:
  html_document:
    theme: cosmo
    toc: yes
---

## Administration

#### Purpose
Refactoring the approach to building a standard survey database.  This script reads in data produced by the legacy SAS procedures and prepares the data for merger with the active data.

#### _ISSUES_

#### _TODO_
1.  Remove Napa Vine once added to Standard

## Overhead

#### Libraries
```{r overhead}
library(knitr)
suppressMessages(library(dplyr))
library(stringr)
library(reshape2)
```

#### Knitr config
```{r config, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

#### Remote file names
```{r file-names}
F_INPUT_CSVDATA = "M:/Data/OnBoard/Data and Reports/_data Legacy/SAS data/regional_ready.csv"
F_INPUT_RDATA   = "M:/Data/OnBoard/Data and Reports/_data Standardized/survey_legacy_additional.RData"

F_OUTPUT_RDATA  = "M:/Data/OnBoard/Data and Reports/_data Standardized/survey_legacy.RData"

```

## Procedure
```{r convert}
# Read in the CSV data
sasdata <- read.csv(F_INPUT_CSVDATA, header = TRUE, stringsAsFactors = FALSE)

# Rename variables to be standard
sasdata.clean <- sasdata %>%
  rename(ID                = id,
         auto_suff         = autoSuff, 
         survey_tech       = survey_mode,
         first_board_tech  = first_transit_mode,
         last_alight_tech  = last_transit_mode,
         approximate_age   = age,
         survey_board_lon  = survey_boarding_x,
         survey_board_lat  = survey_boarding_y,
         survey_alight_lon = survey_alighting_x,                 
         survey_alight_lat = survey_alighting_y,                 
         first_board_lon   = first_boarding_x,                     
         first_board_lat   = first_boarding_y,                     
         last_alight_lon   = last_alighting_x,                     
         last_alight_lat   = last_alighting_y,                     
         home_taz          = homeTAZ,                                     
         workplace_taz     = workTAZ,                                
         school_taz        = schoolTAZ,                                 
         orig_taz          = originTAZ,                                   
         dest_taz          = destTAZ,                                     
         home_maz          = homeMAZ,                                     
         workplace_maz     = workMAZ,                                
         school_maz        = schoolMAZ,                                 
         orig_maz          = originMAZ,                                   
         dest_maz          = destMAZ,                                     
         day_of_the_week   = DAY_OF_THE_WEEK,                      
         day_part          = daypart,                                     
         first_board_tap   = first_boarding_tap,                   
         last_alight_tap   = last_alighting_tap)

# Remove variables we do not need
sasdata.clean <- sasdata.clean %>%
  select(-orig_purp_field, -dest_purp_field, -daypart_start, -daypart_end)
  
# Transformations
sasdata.clean <- sasdata.clean %>%
  rename(field_start_sas = field_start, field_end_sas = field_end) %>%
  mutate(field_start     = as.Date(str_trim(field_start_sas), format = "%m/%d/%Y")) %>%
  mutate(field_end       = as.Date(str_trim(field_end_sas),   format = "%m/%d/%Y")) %>%
  select(-field_start_sas, -field_end_sas) %>%
  mutate(survey_year     = as.numeric(format(field_start, "%Y"))) %>%
  mutate(Unique_ID       = paste(ID, operator, survey_year, sep = "---"))

# Variable re-codes
sasdata.clean <- sasdata.clean %>%
  mutate(auto_suff = ifelse(auto_suff == 'Zero autos',       'zero autos',       auto_suff)) %>%
  mutate(auto_suff = ifelse(auto_suff == 'Workers > autos',  'auto negotiating', auto_suff)) %>%
  mutate(auto_suff = ifelse(auto_suff == 'Workers <= autos', 'auto sufficient',  auto_suff)) %>%
  mutate(auto_suff = ifelse(auto_suff == '.',                'Missing',          auto_suff))

# Join additional variables
load(F_INPUT_RDATA)
legacy.addtl <- legacy.addtl %>%
  select(-ID, -operator, -survey_year)
survey.legacy <- left_join(sasdata.clean, legacy.addtl, by = c("Unique_ID"))

# Manually add entry/exit for ferries
on_off <- survey.legacy %>%
  filter(operator == 'Golden Gate Ferry' | operator == 'SF Bay Ferry') %>%
  select(Unique_ID, route)

on_off <- cbind(on_off, colsplit(on_off$route, "TO", c("onoff_enter_station_update", "onoff_exit_station_update")))
on_off <- select(on_off, -route)

survey.legacy <- left_join(survey.legacy, on_off, by = c("Unique_ID"))

survey.legacy <- survey.legacy %>%
  mutate(onoff_enter_station = ifelse(is.na(onoff_enter_station), str_trim(onoff_enter_station_update), onoff_enter_station)) %>%
  mutate(onoff_exit_station  = ifelse(is.na(onoff_exit_station),  str_trim(onoff_exit_station_update),  onoff_exit_station)) %>%
  select(-onoff_enter_station_update, -onoff_exit_station_update)

table(survey.legacy$onoff_enter_station)
table(survey.legacy$onoff_exit_station)

# Clean up for merge
survey.legacy <- survey.legacy %>%
  select(-vehicles_additional_info, -workers_additional_info)

# Write legacy disk
save(survey.legacy, file = F_OUTPUT_RDATA)
```

